const guide = (points, corrections, takeaway) => Object.freeze({ points, corrections, takeaway });

// These guides are distilled from the organised Notion lesson pages. They are
// intentionally written as teaching notes rather than transcript fragments.
export const DEEP_LESSON_GUIDES = Object.freeze({
  "june-28": guide([
    ["Polite ordering", "丁寧な注文", "Use I’d like + noun and Could I have + noun to order without sounding abrupt.", "I’d like＋名詞 / Could I have＋名詞で、ぶっきらぼうにならずに注文できます。", "I’d like an iced coffee, please.", "アイスコーヒーをお願いします。"],
    ["Ask back naturally", "自然に聞き返す", "How about you? returns the same question. What about you? is also natural in conversation.", "How about you? は同じ質問を相手に返す表現です。What about you? も自然です。", "I’m from Tokyo. How about you?", "私は東京出身です。あなたは？"],
    ["Past questions", "過去の質問", "After did, use the base verb: Did he help? — not Did he helped?", "did の後は動詞の原形です。Did he helped? にはしません。", "Did he help you yesterday?", "彼は昨日あなたを手伝いましたか？"],
    ["Accepting a situation", "仕方がない", "It can’t be helped means the situation cannot be changed; it is not the same as asking for help.", "It can’t be helped は「状況を変えられない＝仕方がない」で、助けを求める意味ではありません。", "The train stopped, but it can’t be helped.", "電車が止まりましたが、仕方がありません。"],
  ], [["I want coffee.", "I’d like a coffee, please."], ["Did he helped you?", "Did he help you?"]], ["Build a polite request, then ask the same question back.", "丁寧にお願いし、How about you? で相手にも聞き返しましょう。"]),
  "june-29": guide([
    ["Four meanings of hear", "hear の使い分け", "I heard it = I heard the sound; I heard that = I received that information; I heard about it = I learned the news; I heard of it = I know it exists.", "I heard it は音、I heard that は情報、I heard about it は詳しい話、I heard of it は存在を知っている、という違いです。", "I’ve heard of the restaurant, but I haven’t been there.", "その店は聞いたことがありますが、行ったことはありません。"],
    ["Natural reactions", "自然なリアクション", "Exactly agrees strongly; That’s so true shows shared feeling; For real? can show surprise.", "Exactly は強い同意、That’s so true は共感、For real? は驚きを表せます。", "Exactly. That’s what I meant.", "その通り。私が言いたかったのはそれです。"],
    ["Position words", "位置の言葉", "Use top right, bottom left and in the middle without extra prepositions when naming a screen position.", "画面の位置なら top right / bottom left / in the middle を使います。", "The button is in the top right.", "ボタンは右上にあります。"],
  ], [["I heard about of it.", "I heard about it."], ["on the top right side", "in the top right"]], ["Choose the hear phrase by asking: sound, information, news, or simple awareness?", "音・情報・詳しい話・存在のどれかを考えて hear の形を選びましょう。"]),
  "june-30": guide([
    ["Feeling or cause", "気持ちか原因か", "-ed describes the person’s feeling; -ing describes the thing that causes it.", "-ed は人の気持ち、-ing はその気持ちを起こす原因です。", "I’m annoyed because the noise is annoying.", "その音がうるさくて、私はイライラしています。"],
    ["Different kinds of irritation", "イライラの種類", "Annoyed is everyday irritation; frustrated is blocked progress; irritated is stronger discomfort; stressed out is pressure.", "annoyed は日常的な苛立ち、frustrated はうまくいかないもどかしさ、irritated は強めの不快感、stressed out は重圧です。", "I’m frustrated because nothing is working.", "何もうまくいかなくて、もどかしいです。"],
    ["Give a reason for preference", "好みと理由", "Use prefer A to B, then add because + a full sentence.", "prefer A to B の後に because＋文を続けると理由まで言えます。", "I prefer tea to coffee because it helps me relax.", "リラックスできるので、コーヒーより紅茶が好きです。"],
  ], [["I’m annoying.", "I’m annoyed."], ["I prefer tea than coffee.", "I prefer tea to coffee."]], ["Name the feeling precisely, then explain what caused it.", "感情を具体的に選び、その原因まで一文で説明しましょう。"]),
  "july-04": guide([
    ["Actually", "actually の役割", "Actually gently corrects, clarifies or adds unexpected information.", "actually は、やわらかい訂正・明確化・意外な情報の追加に使います。", "Actually, I’m free this afternoon.", "実は、今日の午後は空いています。"],
    ["Unexpected changes", "急な予定変更", "Something came up is a natural, private way to say an unexpected matter appeared.", "Something came up は、詳しく言わずに「急用ができた」と伝える自然な表現です。", "Sorry, something came up, so I can’t join.", "すみません、急用ができて参加できません。"],
    ["Possibility", "可能性", "Might and may show possibility; will sounds much more certain.", "might / may は可能性、will はより強い確信を表します。", "It might rain later.", "あとで雨が降るかもしれません。"],
    ["Useful vocabulary", "使える語彙", "Avoid = stay away from; on purpose = intentionally; grateful = thankful; crash can mean collide or suddenly fail.", "avoid は避ける、on purpose はわざと、grateful は感謝している、crash は衝突・停止です。", "I’m grateful that you helped me.", "手伝ってくれて感謝しています。"],
  ], [["I have a something.", "Something came up."], ["I did it by purpose.", "I did it on purpose."]], ["Use actually to clarify and something came up to explain a sudden change naturally.", "actually で補足し、something came up で急な変更を自然に説明しましょう。"]),
  "july-05": guide([
    ["Sentence-final though", "文末の though", "At the end, though means ‘but still’ and softens a contrast in casual speech.", "文末の though は「でもね」に近く、会話で対比をやわらげます。", "It was expensive. It was delicious, though.", "高かったです。でも、おいしかったですよ。"],
    ["Replies to thanks", "お礼への返事", "You’re welcome is standard; No problem is casual; My pleasure sounds warm and polite.", "You’re welcome は基本、No problem はカジュアル、My pleasure は温かく丁寧です。", "Thanks for your help. — My pleasure.", "手伝ってくれてありがとう。— 喜んで。"],
    ["Takeout English", "持ち帰りの英語", "US: takeout/to go. UK: takeaway. A go-to is a reliable favourite and is unrelated to got to.", "米国では takeout / to go、英国では takeaway。go-to は「定番」で、got to とは別です。", "This café is my go-to place for lunch.", "このカフェは昼食の定番です。"],
  ], [["Take away, please. (US)", "To go, please."], ["This is my got-to café.", "This is my go-to café."]], ["Add though at the end to make a spoken contrast sound friendly.", "文末に though を置いて、対比を会話らしくやわらげましょう。"]),
  "july-06": guide([
    ["Yet and finished time", "yet と終わった時間", "Use haven’t + past participle + yet for ‘not up to now’. Use simple past with yesterday or last night.", "今までまだなら haven’t＋過去分詞＋yet、yesterday / last night なら過去形です。", "I haven’t had coffee yet, but I drank tea this morning.", "まだコーヒーは飲んでいませんが、今朝は紅茶を飲みました。"],
    ["Irregular verb: drink", "drink の変化", "The three forms are drink–drank–drunk. Perfect tenses need drunk.", "drink–drank–drunk。完了形では drunk を使います。", "I’ve already drunk two glasses of water.", "もう水を2杯飲みました。"],
    ["Describing light", "光り方の表現", "Sparkling has lively points of light; glittery has many tiny reflections; shiny has a smooth reflected surface.", "sparkling はきらめき、glittery は細かな反射、shiny はつるっと光る表面です。", "The sea is sparkling in the sunlight.", "海が日差しできらきらしています。"],
    ["Small grammar patterns", "小さな文法パターン", "Use hate + -ing, interested for a person, interesting for a thing, and on social media.", "hate＋ing、人は interested、物は interesting、SNS上は on social media です。", "I’m interested in the story I saw on social media.", "SNSで見た話に興味があります。"],
  ], [["I haven’t drank it yet.", "I haven’t drunk it yet."], ["I’m interesting in it.", "I’m interested in it."]], ["Check the time word first; it usually tells you whether to use simple past or present perfect.", "まず時間表現を確認すると、過去形か現在完了かを選びやすくなります。"]),
  "july-07": guide([
    ["Bring and buy", "bring と buy", "Bring–brought–brought means carry something here; buy–bought–bought means purchase.", "bring–brought–brought は持ってくる、buy–bought–bought は買うです。", "I bought a cake and brought it to the office.", "ケーキを買って職場へ持ってきました。"],
    ["Tell someone to do something", "人に〜するよう言う", "The pattern is tell + person + to + base verb.", "tell＋人＋to＋動詞の原形の順です。", "She told me to call later.", "彼女は私にあとで電話するよう言いました。"],
    ["Question word order", "疑問文の語順", "With do/does/did, place the subject before the base verb.", "do / does / did の疑問文では、主語の後に動詞の原形を置きます。", "Why did your phone die?", "どうして携帯の充電が切れたの？"],
    ["Acting for someone", "人の代理", "On my behalf is formal; for me is everyday; instead of me stresses replacement.", "on my behalf は丁寧、for me は日常的、instead of me は交代を強調します。", "Could you attend on my behalf?", "私の代理で出席してもらえますか？"],
  ], [["She told to me call.", "She told me to call."], ["Why your phone died?", "Why did your phone die?"]], ["Keep bring/buy separate, and remember the complete tell + person + to pattern.", "bring / buy を区別し、tell＋人＋to の型をひとまとまりで覚えましょう。"]),
  "july-11": guide([
    ["State: be connected", "接続された状態", "Use be connected for a state and connect for the action.", "be connected は接続状態、connect は接続する動作です。", "The phone is connected to the car.", "携帯は車に接続されています。"],
    ["Live events", "生放送", "Live broadcast is TV/radio; livestream is common for online video; live is pronounced /laɪv/ here.", "live broadcast はテレビ・ラジオ、livestream はオンライン動画でよく使います。この live は「ライブ」と発音します。", "The event will be livestreamed tonight.", "イベントは今夜ライブ配信されます。"],
    ["Notice vs realize", "notice と realize", "Notice is becoming aware through the senses; realize is understanding a fact.", "notice は見聞きして気づく、realize は事実を理解して気づくことです。", "I noticed the sign and realized we were lost.", "看板に気づき、道に迷っていると分かりました。"],
    ["Home words", "故郷の表現", "Hometown is the place you grew up; my parents’ house is the actual family home.", "hometown は育った町、my parents’ house は両親の家そのものです。", "I’m visiting my hometown and staying at my parents’ house.", "故郷を訪れ、両親の家に泊まります。"],
  ], [["The phone connected now.", "The phone is connected now."], ["I realized the sound.", "I noticed the sound."]], ["Use notice for what you detect and realize for what you understand.", "感覚で気づくなら notice、理解して気づくなら realize を使いましょう。"]),
  "july-12": guide([
    ["Have–had–had", "have の3つの形", "Have is the base/present form; had is both past and past participle.", "have は原形・現在形、had は過去形と過去分詞の両方です。", "I had coffee yesterday, but I haven’t had any today.", "昨日はコーヒーを飲みましたが、今日はまだ飲んでいません。"],
    ["Main verb or helper", "一般動詞か助動詞か", "In I have lunch, have means eat/consume. In I have eaten, have is the perfect-tense helper.", "I have lunch の have は食べる、I have eaten の have は完了形を作る助動詞です。", "I’ve already had lunch.", "もう昼食を食べました。"],
    ["Any and yet", "any と yet", "Any is common in questions/negatives; yet means up to now and usually comes at the end.", "any は疑問・否定文、yet は「今までまだ」で通常文末です。", "Have you had any water yet?", "もう何か水を飲みましたか？"],
  ], [["I haven’t have any today.", "I haven’t had any today."], ["I didn’t had lunch.", "I didn’t have lunch."]], ["After have/has in a perfect tense, choose the past participle: had, not have.", "完了形の have / has の後は過去分詞 had を使います。"]),
  "july-13": guide([
    ["Might vs will", "might と will", "Might is uncertain possibility; will is a confident prediction or decision.", "might は不確かな可能性、will は確信のある予測・意志です。", "I might be late, but I’ll call you.", "遅れるかもしれませんが、電話します。"],
    ["Approximate time", "おおよその時間", "At this time is specific; around this time means approximately this hour or season.", "at this time は特定の時点、around this time はこの時間帯・時期ごろです。", "The streets are usually packed around this time.", "この時間帯はたいてい道が混んでいます。"],
    ["Movement and traffic", "移動と交通", "Rush back means return quickly; go back is neutral; a signal can be a traffic light or transmitted sign.", "rush back は急いで戻る、go back は普通に戻る。signal は信号・合図です。", "I had to rush back before the traffic got worse.", "渋滞がひどくなる前に急いで戻る必要がありました。"],
    ["Week expressions", "週の表現", "At the beginning/end of the week describes a period; unusual means not normal.", "at the beginning/end of the week は週の初め・終わり、unusual はいつもと違うです。", "It was unusually quiet at the beginning of the week.", "週の初めは珍しく静かでした。"],
  ], [["I will maybe be late.", "I might be late."], ["in around this time", "around this time"]], ["Match certainty to might or will, then add a clear time phrase.", "確信度で might / will を選び、明確な時間表現を加えましょう。"]),
  "july-18": guide([
    ["Be supposed to", "〜することになっている", "Use be supposed to for plans, rules or expectations; change be for the subject and tense.", "be supposed to は予定・規則・期待。主語と時制に合わせて be を変えます。", "We’re supposed to meet at ten.", "10時に会うことになっています。"],
    ["Do/does and have/has", "主語との一致", "Do/does starts ordinary-verb questions; have/has forms the present perfect.", "do / does は一般動詞の疑問文、have / has は現在完了を作ります。", "Does he have a car? Has he arrived yet?", "彼は車を持っていますか？ もう到着しましたか？"],
    ["Emphatic do", "強調の do", "I do like it strongly confirms a positive fact, often after doubt or correction.", "I do like it は、疑いや訂正の後で肯定を強調します。", "I do want to go, but I’m busy.", "本当に行きたいのですが、忙しいです。"],
    ["Fire expressions", "火事の表現", "Catch fire = begin burning; be on fire = burning now; start a fire = cause a fire.", "catch fire は燃え始める、be on fire は燃えている、start a fire は火事を起こすです。", "The stove caught fire, but nobody was hurt.", "コンロから火が出ましたが、けが人はいませんでした。"],
  ], [["He supposed to come.", "He is supposed to come."], ["The stove was catch fire.", "The stove caught fire."]], ["Use be supposed to as one complete pattern, and keep the three fire expressions separate.", "be supposed to を一つの型で覚え、3つの火の表現を区別しましょう。"]),
  "july-19": guide([
    ["Both, either, neither", "2つの選択", "Both = the two; either = one or the other/whichever; neither = not this one and not that one.", "both は両方、either はどちらか・どちらでも、neither はどちらも〜ないです。", "Either is fine, but neither is available today.", "どちらでも構いませんが、今日はどちらも空いていません。"],
    ["Preference", "好み", "Prefer A to B is neutral. Would rather + base verb is conversational. Use rather than for the rejected option.", "prefer A to B は基本形、would rather＋原形は会話的。比較相手は rather than で続けます。", "I’d rather stay home than go out.", "外出するより家にいたいです。"],
    ["Natural reactions", "自然な反応", "Hilarious means extremely funny; crack me up means make me laugh a lot.", "hilarious はとても面白い、crack me up は大笑いさせるです。", "That video cracks me up every time.", "その動画を見ると毎回大笑いします。"],
    ["Everyday movement", "日常の移動", "Run into = meet unexpectedly; on my way = travelling to the destination now.", "run into は偶然会う、on my way は目的地へ向かっている途中です。", "I ran into Ken on my way home.", "帰宅途中にケンに偶然会いました。"],
  ], [["I prefer tea than coffee.", "I prefer tea to coffee."], ["I would rather to stay.", "I would rather stay."]], ["For two choices, decide whether you mean two, one, or zero: both, either, or neither.", "2つ・1つ・0のどれを表すかで both / either / neither を選びましょう。"]),
  "july-22": guide([
    ["Would you be available?", "丁寧な予定確認", "Would is a modal, so the next verb is the base form be—not are or is.", "would は助動詞なので、後ろは are / is ではなく原形 be です。", "Would you be available on August 4th at 10 a.m.?", "8月4日の午前10時はご都合いかがですか？"],
    ["You and you guys", "単数・複数の you", "You can be singular or plural. You guys or you all makes a plural audience explicit and is casual.", "you は単数・複数の両方。you guys / you all は複数だとはっきり示すカジュアルな表現です。", "Are you all ready?", "皆さん、準備はできましたか？"],
    ["Negative questions", "否定疑問文", "English yes confirms a positive fact; no confirms a negative fact, even if the question is negative.", "英語の Yes は肯定の事実、No は否定の事実を表します。質問が否定形でも同じです。", "Don’t you like it? — Yes, I do.", "好きじゃないの？— いいえ、好きです。"],
    ["Right? and safe replies", "right? への安全な返事", "After a negative statement + right?, answer the whole claim with That’s right or correct it with Actually…", "否定文＋right? では、同意なら That’s right、訂正なら Actually… が明確です。", "You don’t like it, right? — Actually, I do.", "好きじゃないんですよね？— 実は好きです。"],
  ], [["Would you are available?", "Would you be available?"], ["Yes. (ambiguous)", "That’s right. I don’t like it."]], ["With negative questions, finish the answer: Yes, I do / No, I don’t / That’s right / Actually…", "否定疑問では Yes / No だけで終わらず、後ろまで言いましょう。"]),
  "july-23": guide([
    ["Present perfect", "現在完了", "Use have + past participle for a past action connected to now. Simple past I just ordered is also common; I’ve just ordered highlights the current result.", "現在完了は have＋過去分詞。I just ordered も自然で、I’ve just ordered は今の結果を強調します。", "I haven’t thought of a title yet.", "まだタイトルを考えていません。"],
    ["Under the weather", "体調が悪い", "This idiom means feeling slightly ill, not literal weather.", "天気の下ではなく「少し体調が悪い」というイディオムです。", "I’m feeling under the weather today.", "今日は少し体調が悪いです。"],
    ["Too + adjective + to", "〜すぎてできない", "Too hot to go outside means the heat prevents going out. Difficult to go outside is possible but less specific.", "too hot to go outside は暑さが外出を妨げる意味。difficult は原因がより曖昧です。", "It’s too hot to go outside.", "暑すぎて外に出られません。"],
    ["Natural nouns and movement", "自然な名詞・移動表現", "Say chicken-and-egg rice bowl, pork cutlet rice bowl, came out of nowhere, lying on the floor, and go/get back home.", "chicken-and-egg rice bowl、came out of nowhere、lying on the floor、get back home などを自然に使います。", "A car came out of nowhere, but I got home safely.", "車が突然現れましたが、無事に帰宅しました。"],
    ["Doraemon English", "ドラえもん英語", "Doraemon is a cat-shaped robot with three whiskers and no ears. Key terms: Bamboo Copter and Anywhere Door.", "ドラえもんはひげが3本で耳のない猫型ロボット。Bamboo Copter / Anywhere Door が重要語です。", "Doraemon uses the Anywhere Door to travel instantly.", "ドラえもんはどこでもドアで一瞬にして移動します。"],
  ], [["I have think.", "I haven’t thought of one yet."], ["The car suddenly came up.", "A car came out of nowhere."], ["I’m going back to my home.", "I’m going back home."]], ["Connect grammar to real scenes: recent actions, weather, lunch, movement and Doraemon.", "最近の行動・天気・食事・移動・ドラえもんの場面で文法を使いましょう。"]),
  "july-25": guide([
    ["Hunger levels", "空腹の強さ", "Hungry is neutral; getting hungry shows a change; starving is a strong casual exaggeration.", "hungry は状態、getting hungry は変化、starving は「腹ぺこ」の強い会話表現です。", "I’m getting hungry. I’ll be starving by six.", "お腹が空いてきました。6時には腹ぺこになりそうです。"],
    ["Irritation and anger", "苛立ちと怒り", "Annoyed is mild irritation; frustrated is blocked progress; angry is clear anger. Got angry focuses on the change.", "annoyed は軽い苛立ち、frustrated はもどかしさ、angry は明確な怒り。got angry は怒り始めた変化です。", "I got angry when he lied to me.", "彼が嘘をついたとき腹が立ちました。"],
    ["Nerves and nervous", "nerves と nervous", "Nerves is a noun; nervous is an adjective. Get on my nerves means annoy me, while make me nervous means make me anxious.", "nerves は名詞、nervous は形容詞。get on my nerves はイライラ、make me nervous は不安にさせるです。", "The noise gets on my nerves, but the interview makes me nervous.", "音にはイライラしますが、面接には緊張します。"],
    ["Get + adjective", "状態の変化", "Be + adjective is a state; be getting + adjective is a change happening now; got + adjective is a past change.", "be＋形容詞は状態、be getting＋形容詞は進行中の変化、got＋形容詞は過去の変化です。", "It’s getting cold, and I’m getting tired.", "寒くなってきて、疲れてきました。"],
    ["People words and intuition", "人を表す語・直感", "Someone/anyone/no one/everyone are grammatically singular. A gut feeling is an intuitive feeling without clear evidence.", "someone / anyone / no one / everyone は文法上単数。gut feeling は根拠を説明できない直感です。", "No one knows, but I have a gut feeling he’ll come.", "誰も知りませんが、彼が来るような気がします。"],
  ], [["I am not getin hungry.", "I’m not getting hungry."], ["He makes me nerves.", "He makes me nervous."], ["Everyone are ready.", "Everyone is ready."]], ["Use state, change and cause precisely: I’m annoyed / I’m getting annoyed / It’s annoying.", "状態・変化・原因を、I’m annoyed / I’m getting annoyed / It’s annoying で区別しましょう。"]),
  "july-26": guide([
    ["Hope vs wish", "hope と wish", "Hope is for a possible result; wish contrasts with reality or regrets an unchangeable past.", "hope は実現可能なこと、wish は現実と違う願い・変えられない過去への後悔です。", "I hope I can visit Malaysia next year. I wish I were there now.", "来年マレーシアへ行けるといいです。今そこにいたらいいのに。"],
    ["Wish about now", "現在についての wish", "Use wish + past form for a present unreal situation. Were is the formal form; was is common in conversation.", "現在の非現実は wish＋過去形。were が正式で、会話では was もよく使われます。", "I wish I were in Malaysia.", "マレーシアにいたらいいのに。"],
    ["Wish about the past", "過去への後悔", "Use wish + had + past participle. Born needs be, so it becomes had been born.", "過去への後悔は wish＋had＋過去分詞。born は be born なので had been born です。", "I wish I had been more careful.", "もっと注意しておけばよかった。"],
    ["Present vs past perfect", "現在完了と過去完了", "Present perfect looks back from now; past perfect looks back from a past point to an earlier event.", "現在完了は今を基準に過去を見る。過去完了は過去の時点からさらに前を見ます。", "I have eaten. / I had eaten before he arrived.", "もう食べました。／彼が来る前に食べ終えていました。"],
    ["Yet and simple past", "yet と過去形", "I haven’t taken a bath yet means not up to now. I didn’t take one last night reports a finished past period and says nothing definite about the future.", "haven’t…yet は今までまだ、didn’t…last night は終わった過去。今後の予定までは示しません。", "I haven’t showered yet, but I’ll do it later.", "まだシャワーを浴びていませんが、あとで浴びます。"],
  ], [["I wish I have been born…", "I wish I had been born…"], ["I haven’t took a bath yet.", "I haven’t taken a bath yet."], ["I have seen him yesterday.", "I saw him yesterday."]], ["Find the time viewpoint first: possible future, unreal present, now-connected past, or earlier past.", "可能な未来・非現実の現在・今につながる過去・過去より前、どれかを先に判断しましょう。"]),
  "july-27": guide([
    ["Spill, pour, splash", "液体の動き", "Spill is usually accidental; pour is controlled and intentional; splash sends liquid with force.", "spill は主にうっかり、pour は意図的に注ぐ、splash は勢いよくかけるです。", "I spilled coffee on my shirt, so I poured another cup.", "シャツにコーヒーをこぼしたので、もう一杯注ぎました。"],
    ["An acquired taste", "慣れると好きになる味", "Use an acquired taste for something people learn to enjoy. Sophisticated flavor means refined; more for adults means adult-oriented.", "an acquired taste は慣れると好きになる味、sophisticated flavor は洗練された味、more for adults は大人向けです。", "Black coffee can be an acquired taste.", "ブラックコーヒーは慣れると好きになる味です。"],
    ["Three time viewpoints", "3つの時制", "Simple past = finished past; present perfect = linked to now; past perfect = earlier than another past event.", "過去形は終わった過去、現在完了は今とのつながり、過去完了は別の過去より前です。", "I ate at seven. / I’ve eaten. / I had eaten before he called.", "7時に食べた。／もう食べた。／彼が電話する前に食べていた。"],
    ["Yet, didn’t, never", "まだ・しなかった・一度もない", "Haven’t…yet leaves the present task open; didn’t reports a past non-action; have never describes life experience.", "haven’t…yet は今までまだ、didn’t は過去にしなかった、have never は今まで一度もないです。", "I haven’t watched it yet. I didn’t watch it yesterday. I’ve never seen the series.", "まだ見ていません。昨日は見ませんでした。そのシリーズは一度も見たことがありません。"],
    ["Used to and irregular verbs", "過去の習慣・不規則動詞", "Used to + base verb describes a past habit/state that is no longer true. Perfect tenses require past participles such as gone, eaten and taken.", "used to＋原形は今は違う過去の習慣・状態。完了形では gone / eaten / taken など過去分詞を使います。", "I used to drink tea, but I’ve started drinking coffee.", "以前は紅茶を飲んでいましたが、コーヒーを飲み始めました。"],
  ], [["I spilled coffee to my shirt.", "I spilled coffee on my shirt."], ["It is an adult taste.", "It is an acquired taste."], ["I had ate dinner.", "I had eaten dinner."]], ["Choose the verb by intention and the tense by the time you are looking from.", "意図で動詞を選び、どの時点から見るかで時制を選びましょう。"]),
});
