-- Premium topic choices and selected-topic persistence.
-- Generated from scripts/premium-topic-manifest.mjs. Do not edit topic JSON here.

alter table public.review_premium_tasks
  add column if not exists topics jsonb not null default '[]'::jsonb;

alter table public.review_task_submissions
  add column if not exists selected_topic_key text;

do $constraints$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_premium_tasks'::regclass
      and conname = 'review_premium_tasks_topics_array'
  ) then
    alter table public.review_premium_tasks
      add constraint review_premium_tasks_topics_array
      check (jsonb_typeof(topics) = 'array');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.review_task_submissions'::regclass
      and conname = 'review_task_submissions_topic_key_length'
  ) then
    alter table public.review_task_submissions
      add constraint review_task_submissions_topic_key_length
      check (selected_topic_key is null or length(btrim(selected_topic_key)) between 1 and 100);
  end if;
end;
$constraints$;

do $topics$
declare
  updated_count integer;
begin
  with source(slug, topics) as (
    values
    ('june-28', '[{"key":"cafe-order","title_en":"A café order","title_ja":"カフェでの注文","description_en":"A café order you would enjoy and how you would ask politely.","description_ja":"カフェで楽しみたい注文と、丁寧な頼み方","speaking_prompt_en":"Speak for 60–90 seconds about a café order you would enjoy and how you would ask politely. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"カフェで楽しみたい注文と、丁寧な頼み方について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a café order you would enjoy and how you would ask politely. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"カフェで楽しみたい注文と、丁寧な頼み方について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’d like …, please.","Could I have …?","That’s all, thank you."],"vocabulary":["order","recommendation","decaf","takeaway"]},{"key":"polite-decline","title_en":"A polite no","title_ja":"丁寧な断り方","description_en":"A time you needed to decline an invitation without sounding unfriendly.","description_ja":"相手を嫌な気持ちにさせず、誘いを断った経験","speaking_prompt_en":"Speak for 60–90 seconds about a time you needed to decline an invitation without sounding unfriendly. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"相手を嫌な気持ちにさせず、誘いを断った経験について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a time you needed to decline an invitation without sounding unfriendly. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"相手を嫌な気持ちにさせず、誘いを断った経験について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Thank you, but …","I’m afraid I can’t.","Maybe another time."],"vocabulary":["invitation","schedule","decline","alternative"]},{"key":"customer-care","title_en":"Good customer service","title_ja":"良い接客","description_en":"What makes service at a café or shop feel thoughtful and welcoming.","description_ja":"カフェや店で、気配りのある接客だと感じること","speaking_prompt_en":"Speak for 60–90 seconds about what makes service at a café or shop feel thoughtful and welcoming. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"カフェや店で、気配りのある接客だと感じることについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about what makes service at a café or shop feel thoughtful and welcoming. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"カフェや店で、気配りのある接客だと感じることについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["How can I help?","Would you like anything else?","I appreciate it."],"vocabulary":["service","welcoming","attentive","request"]}]'::jsonb),
    ('june-29', '[{"key":"misheard-message","title_en":"A message you misheard","title_ja":"聞き間違えたメッセージ","description_en":"A misunderstanding caused by hearing one word or detail incorrectly.","description_ja":"単語や細部の聞き間違いから生まれた誤解","speaking_prompt_en":"Speak for 60–90 seconds about a misunderstanding caused by hearing one word or detail incorrectly. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"単語や細部の聞き間違いから生まれた誤解について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a misunderstanding caused by hearing one word or detail incorrectly. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"単語や細部の聞き間違いから生まれた誤解について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I thought you said …","Could you say that again?","Now I understand."],"vocabulary":["misunderstanding","detail","clarify","announcement"]},{"key":"surprising-news","title_en":"Surprising news","title_ja":"驚いた知らせ","description_en":"News that surprised you and how you reacted when you first heard it.","description_ja":"驚いた知らせと、それを初めて聞いたときの反応","speaking_prompt_en":"Speak for 60–90 seconds about news that surprised you and how you reacted when you first heard it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"驚いた知らせと、それを初めて聞いたときの反応について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about news that surprised you and how you reacted when you first heard it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"驚いた知らせと、それを初めて聞いたときの反応について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I couldn’t believe it.","That was unexpected.","I heard that …"],"vocabulary":["reaction","rumour","confirmed","unexpected"]},{"key":"finding-position","title_en":"Finding the right place","title_ja":"場所を見つける","description_en":"How you would explain where a person or object is positioned.","description_ja":"人や物がどこにあるかを、分かりやすく説明する方法","speaking_prompt_en":"Speak for 60–90 seconds about how you would explain where a person or object is positioned. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"人や物がどこにあるかを、分かりやすく説明する方法について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how you would explain where a person or object is positioned. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"人や物がどこにあるかを、分かりやすく説明する方法について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["It’s next to …","You’ll see it on your left.","It’s directly behind …"],"vocabulary":["position","opposite","beside","landmark"]}]'::jsonb),
    ('june-30', '[{"key":"stadium-feelings","title_en":"A memorable match","title_ja":"印象に残った試合","description_en":"A sports match that changed your mood while you were watching it.","description_ja":"見ている間に気持ちが変化した、印象的なスポーツの試合","speaking_prompt_en":"Speak for 60–90 seconds about a sports match that changed your mood while you were watching it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"見ている間に気持ちが変化した、印象的なスポーツの試合について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a sports match that changed your mood while you were watching it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"見ている間に気持ちが変化した、印象的なスポーツの試合について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I was excited when …","It was frustrating because …","In the end, …"],"vocabulary":["supporter","equaliser","frustrated","atmosphere"]},{"key":"everyday-annoyance","title_en":"An everyday annoyance","title_ja":"日常のちょっとした不満","description_en":"A small everyday problem that annoys you and a reasonable solution.","description_ja":"日常で少し困ることと、現実的な解決方法","speaking_prompt_en":"Speak for 60–90 seconds about a small everyday problem that annoys you and a reasonable solution. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"日常で少し困ることと、現実的な解決方法について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a small everyday problem that annoys you and a reasonable solution. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"日常で少し困ることと、現実的な解決方法について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’m annoyed by …","What bothers me is …","It would help if …"],"vocabulary":["noise","habit","solution","considerate"]},{"key":"personal-preference","title_en":"A preference that matters","title_ja":"大切にしている好み","description_en":"A choice where your personal preference is stronger than other people’s advice.","description_ja":"周りの意見より、自分の好みを大切にした選択","speaking_prompt_en":"Speak for 60–90 seconds about a choice where your personal preference is stronger than other people’s advice. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"周りの意見より、自分の好みを大切にした選択について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a choice where your personal preference is stronger than other people’s advice. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"周りの意見より、自分の好みを大切にした選択について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I prefer … to …","For me, … works better.","It depends on …"],"vocabulary":["preference","priority","option","recommendation"]}]'::jsonb),
    ('july-04', '[{"key":"unexpected-delay","title_en":"When plans changed","title_ja":"予定が変わったとき","description_en":"An unexpected delay or problem that changed your plans.","description_ja":"予想外の遅れや問題で、予定が変わった経験","speaking_prompt_en":"Speak for 60–90 seconds about an unexpected delay or problem that changed your plans. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"予想外の遅れや問題で、予定が変わった経験について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about an unexpected delay or problem that changed your plans. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"予想外の遅れや問題で、予定が変わった経験について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Something came up.","I ended up …","Luckily, …"],"vocabulary":["delay","reschedule","unexpected","manage"]},{"key":"helpful-stranger","title_en":"Help at the right moment","title_ja":"助けてもらった瞬間","description_en":"A time someone helped you when everyday life did not go as planned.","description_ja":"日常が思いどおりにいかないとき、誰かに助けてもらった経験","speaking_prompt_en":"Speak for 60–90 seconds about a time someone helped you when everyday life did not go as planned. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"日常が思いどおりにいかないとき、誰かに助けてもらった経験について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a time someone helped you when everyday life did not go as planned. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"日常が思いどおりにいかないとき、誰かに助けてもらった経験について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I was having trouble with …","Someone offered to …","It made a difference."],"vocabulary":["assistance","kindness","situation","relieved"]},{"key":"backup-plan","title_en":"Your backup plan","title_ja":"自分の予備プラン","description_en":"How you prepare a practical backup plan for work, travel or daily life.","description_ja":"仕事・旅行・日常生活で、現実的な予備プランを準備する方法","speaking_prompt_en":"Speak for 60–90 seconds about how you prepare a practical backup plan for work, travel or daily life. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"仕事・旅行・日常生活で、現実的な予備プランを準備する方法について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how you prepare a practical backup plan for work, travel or daily life. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"仕事・旅行・日常生活で、現実的な予備プランを準備する方法について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Just in case, …","If that happens, …","My alternative is …"],"vocabulary":["backup","prepare","alternative","reliable"]}]'::jsonb),
    ('july-05', '[{"key":"quick-reaction","title_en":"Your first reaction","title_ja":"最初の反応","description_en":"A situation where your first reaction changed after you learned more.","description_ja":"詳しく知るうちに、最初の反応が変わった出来事","speaking_prompt_en":"Speak for 60–90 seconds about a situation where your first reaction changed after you learned more. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"詳しく知るうちに、最初の反応が変わった出来事について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a situation where your first reaction changed after you learned more. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"詳しく知るうちに、最初の反応が変わった出来事について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["At first, I thought …","Then I realised …","Now I feel …"],"vocabulary":["reaction","impression","realise","perspective"]},{"key":"difficult-choice","title_en":"A difficult everyday choice","title_ja":"日常の迷う選択","description_en":"A recent choice between two reasonable options and how you decided.","description_ja":"どちらも悪くない2つの選択肢から、最近1つを選んだ経験","speaking_prompt_en":"Speak for 60–90 seconds about a recent choice between two reasonable options and how you decided. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"どちらも悪くない2つの選択肢から、最近1つを選んだ経験について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a recent choice between two reasonable options and how you decided. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"どちらも悪くない2つの選択肢から、最近1つを選んだ経験について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I wasn’t sure whether to …","I decided on …","The main reason was …"],"vocabulary":["option","advantage","drawback","decision"]},{"key":"thinking-time","title_en":"Asking for time","title_ja":"考える時間をもらう","description_en":"Why taking time before answering can lead to a better decision.","description_ja":"返事の前に考える時間を取ると、より良い判断につながる理由","speaking_prompt_en":"Speak for 60–90 seconds about why taking time before answering can lead to a better decision. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"返事の前に考える時間を取ると、より良い判断につながる理由について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about why taking time before answering can lead to a better decision. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"返事の前に考える時間を取ると、より良い判断につながる理由について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Let me think about it.","I’m not ready to decide yet.","I’ll get back to you."],"vocabulary":["consider","pressure","deadline","response"]}]'::jsonb),
    ('july-06', '[{"key":"natural-conversation","title_en":"A smoother conversation","title_ja":"会話をなめらかにする","description_en":"What helps an English conversation sound connected rather than word by word.","description_ja":"英語の会話を単語ごとではなく、なめらかに聞こえさせる工夫","speaking_prompt_en":"Speak for 60–90 seconds about what helps an English conversation sound connected rather than word by word. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"英語の会話を単語ごとではなく、なめらかに聞こえさせる工夫について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about what helps an English conversation sound connected rather than word by word. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"英語の会話を単語ごとではなく、なめらかに聞こえさせる工夫について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["What do you mean?","That makes sense.","Go on."],"vocabulary":["rhythm","connected speech","pause","intonation"]},{"key":"keeping-talking","title_en":"Keeping a conversation going","title_ja":"会話を続けるコツ","description_en":"Questions and reactions you use to keep a friendly conversation moving.","description_ja":"親しい会話を止めずに続けるための質問や反応","speaking_prompt_en":"Speak for 60–90 seconds about questions and reactions you use to keep a friendly conversation moving. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"親しい会話を止めずに続けるための質問や反応について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about questions and reactions you use to keep a friendly conversation moving. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"親しい会話を止めずに続けるための質問や反応について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["How about you?","Really? What happened?","That sounds …"],"vocabulary":["follow-up","interest","response","conversation"]},{"key":"clarifying-meaning","title_en":"Checking the meaning","title_ja":"意味を確認する","description_en":"A time you needed to clarify someone’s meaning before responding.","description_ja":"返事をする前に、相手の意味を確認する必要があった場面","speaking_prompt_en":"Speak for 60–90 seconds about a time you needed to clarify someone’s meaning before responding. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"返事をする前に、相手の意味を確認する必要があった場面について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a time you needed to clarify someone’s meaning before responding. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"返事をする前に、相手の意味を確認する必要があった場面について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Do you mean …?","So, are you saying …?","Let me make sure I understand."],"vocabulary":["clarify","intention","assumption","confirm"]}]'::jsonb),
    ('july-07', '[{"key":"thoughtful-gift","title_en":"A thoughtful gift","title_ja":"気持ちのこもった贈り物","description_en":"Something you bought or brought for another person and why you chose it.","description_ja":"誰かのために買ったり持っていったりした物と、それを選んだ理由","speaking_prompt_en":"Speak for 60–90 seconds about something you bought or brought for another person and why you chose it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"誰かのために買ったり持っていったりした物と、それを選んだ理由について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about something you bought or brought for another person and why you chose it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"誰かのために買ったり持っていったりした物と、それを選んだ理由について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I bought this for …","I brought you …","I thought you might like it."],"vocabulary":["gift","souvenir","thoughtful","choose"]},{"key":"helping-someone","title_en":"Doing something for someone","title_ja":"人のためにしたこと","description_en":"A practical thing you did on someone’s behalf.","description_ja":"誰かの代わりに、または誰かのためにした実用的なこと","speaking_prompt_en":"Speak for 60–90 seconds about a practical thing you did on someone’s behalf. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"誰かの代わりに、または誰かのためにした実用的なことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a practical thing you did on someone’s behalf. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"誰かの代わりに、または誰かのためにした実用的なことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I did it for …","Let me take care of it.","I was happy to help."],"vocabulary":["behalf","favour","responsibility","support"]},{"key":"bring-or-buy","title_en":"Planning what to bring","title_ja":"持ち物を考える","description_en":"How you decide what to bring and what to buy for a visit or event.","description_ja":"訪問やイベントで、持参する物と買う物をどう決めるか","speaking_prompt_en":"Speak for 60–90 seconds about how you decide what to bring and what to buy for a visit or event. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"訪問やイベントで、持参する物と買う物をどう決めるかについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how you decide what to bring and what to buy for a visit or event. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"訪問やイベントで、持参する物と買う物をどう決めるかについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I’ll bring …","We need to buy …","Do you already have …?"],"vocabulary":["supplies","prepare","purchase","occasion"]}]'::jsonb),
    ('july-11', '[{"key":"staying-connected","title_en":"Staying connected","title_ja":"つながりを保つ","description_en":"How technology helps you stay connected with people who live far away.","description_ja":"遠くに住む人とのつながりを、テクノロジーがどう支えるか","speaking_prompt_en":"Speak for 60–90 seconds about how technology helps you stay connected with people who live far away. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"遠くに住む人とのつながりを、テクノロジーがどう支えるかについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how technology helps you stay connected with people who live far away. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"遠くに住む人とのつながりを、テクノロジーがどう支えるかについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["We keep in touch through …","It helps us stay connected.","We usually catch up …"],"vocabulary":["connection","video call","distance","regularly"]},{"key":"live-experience","title_en":"Live or recorded?","title_ja":"ライブか録画か","description_en":"Whether you prefer a live event or a recording and why.","description_ja":"イベントはライブと録画のどちらが好きか、その理由","speaking_prompt_en":"Speak for 60–90 seconds about whether you prefer a live event or a recording and why. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"イベントはライブと録画のどちらが好きか、その理由について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about whether you prefer a live event or a recording and why. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"イベントはライブと録画のどちらが好きか、その理由について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’d rather watch it live.","A recording is convenient because …","The atmosphere is …"],"vocabulary":["broadcast","stream","audience","atmosphere"]},{"key":"notice-a-change","title_en":"A change you noticed","title_ja":"気づいた変化","description_en":"A small change you noticed late and what made you realise it.","description_ja":"少し遅れて気づいた小さな変化と、気づくきっかけ","speaking_prompt_en":"Speak for 60–90 seconds about a small change you noticed late and what made you realise it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"少し遅れて気づいた小さな変化と、気づくきっかけについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a small change you noticed late and what made you realise it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"少し遅れて気づいた小さな変化と、気づくきっかけについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I noticed that …","I didn’t realise until …","Something seemed different."],"vocabulary":["notice","realise","detail","gradual"]}]'::jsonb),
    ('july-12', '[{"key":"learning-progress","title_en":"Progress so far","title_ja":"これまでの上達","description_en":"Something you have improved at and what helped you make progress.","description_ja":"上達したことと、進歩につながった方法","speaking_prompt_en":"Speak for 60–90 seconds about something you have improved at and what helped you make progress. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"上達したことと、進歩につながった方法について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about something you have improved at and what helped you make progress. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"上達したことと、進歩につながった方法について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’ve improved …","I haven’t mastered it yet.","What has helped most is …"],"vocabulary":["progress","practice","achievement","yet"]},{"key":"past-experience","title_en":"An experience you had","title_ja":"これまでの経験","description_en":"A past experience that changed how you do something now.","description_ja":"今の行動を変えるきっかけになった過去の経験","speaking_prompt_en":"Speak for 60–90 seconds about a past experience that changed how you do something now. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"今の行動を変えるきっかけになった過去の経験について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a past experience that changed how you do something now. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"今の行動を変えるきっかけになった過去の経験について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I had never … before.","After that, I …","It has changed …"],"vocabulary":["experience","lesson","previously","since"]},{"key":"not-yet","title_en":"A goal not reached yet","title_ja":"まだ達成していない目標","description_en":"A useful goal you have not achieved yet and your next step.","description_ja":"まだ達成していない実用的な目標と、次にすること","speaking_prompt_en":"Speak for 60–90 seconds about a useful goal you have not achieved yet and your next step. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"まだ達成していない実用的な目標と、次にすることについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a useful goal you have not achieved yet and your next step. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"まだ達成していない実用的な目標と、次にすることについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I haven’t … yet.","I’ve already started …","My next step is …"],"vocabulary":["goal","milestone","already","plan"]}]'::jsonb),
    ('july-13', '[{"key":"possible-plan","title_en":"A possible plan","title_ja":"実現するかもしれない予定","description_en":"A plan that might happen and what needs to be decided first.","description_ja":"実現するかもしれない予定と、先に決める必要があること","speaking_prompt_en":"Speak for 60–90 seconds about a plan that might happen and what needs to be decided first. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"実現するかもしれない予定と、先に決める必要があることについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a plan that might happen and what needs to be decided first. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"実現するかもしれない予定と、先に決める必要があることについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I might …","There’s a chance that …","It depends on …"],"vocabulary":["possibility","arrangement","confirm","condition"]},{"key":"best-time","title_en":"The best time of day","title_ja":"一番過ごしやすい時間帯","description_en":"Which part of the day suits you best for work, study or relaxation.","description_ja":"仕事・勉強・休憩に一番合う時間帯","speaking_prompt_en":"Speak for 60–90 seconds about which part of the day suits you best for work, study or relaxation. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"仕事・勉強・休憩に一番合う時間帯について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about which part of the day suits you best for work, study or relaxation. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"仕事・勉強・休憩に一番合う時間帯について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’m most productive …","Around midday, …","Late at night, …"],"vocabulary":["morning","midday","evening","productive"]},{"key":"city-moment","title_en":"A moment in the city","title_ja":"街での出来事","description_en":"A small problem or discovery you experienced while moving around a city.","description_ja":"街を移動しているときに経験した、小さな問題や発見","speaking_prompt_en":"Speak for 60–90 seconds about a small problem or discovery you experienced while moving around a city. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"街を移動しているときに経験した、小さな問題や発見について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a small problem or discovery you experienced while moving around a city. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"街を移動しているときに経験した、小さな問題や発見について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I had to rush back.","I was on my way to …","I suddenly realised …"],"vocabulary":["commute","entrance","crowded","direction"]}]'::jsonb),
    ('july-18', '[{"key":"missed-obligation","title_en":"A plan you missed","title_ja":"できなかった予定","description_en":"Something you were supposed to do but could not complete.","description_ja":"する予定だったのに、できなかったこと","speaking_prompt_en":"Speak for 60–90 seconds about something you were supposed to do but could not complete. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"する予定だったのに、できなかったことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about something you were supposed to do but could not complete. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"する予定だったのに、できなかったことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I was supposed to …","I couldn’t because …","I should have …"],"vocabulary":["obligation","deadline","explanation","reschedule"]},{"key":"asking-for-help","title_en":"Getting the right help","title_ja":"必要な助けを求める","description_en":"A situation where a helper or professional made a difficult moment easier.","description_ja":"困ったときに、専門家や周りの人の助けで楽になった場面","speaking_prompt_en":"Speak for 60–90 seconds about a situation where a helper or professional made a difficult moment easier. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"困ったときに、専門家や周りの人の助けで楽になった場面について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a situation where a helper or professional made a difficult moment easier. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"困ったときに、専門家や周りの人の助けで楽になった場面について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Could you help me with …?","I need someone who can …","Thank you for stepping in."],"vocabulary":["assistant","emergency service","support","responsibility"]},{"key":"fire-safety","title_en":"Responding safely","title_ja":"安全に対応する","description_en":"What people should do first if they notice a fire or another emergency.","description_ja":"火災などの緊急事態に気づいたとき、最初にすべきこと","speaking_prompt_en":"Speak for 60–90 seconds about what people should do first if they notice a fire or another emergency. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"火災などの緊急事態に気づいたとき、最初にすべきことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about what people should do first if they notice a fire or another emergency. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"火災などの緊急事態に気づいたとき、最初にすべきことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["The building is on fire.","We need to leave now.","Call the fire department."],"vocabulary":["evacuate","alarm","emergency exit","firefighter"]}]'::jsonb),
    ('july-19', '[{"key":"either-plan","title_en":"Two workable plans","title_ja":"どちらでもよい予定","description_en":"Two plans that would both work and how you would respond clearly.","description_ja":"どちらでも問題ない2つの予定と、分かりやすい返答","speaking_prompt_en":"Speak for 60–90 seconds about two plans that would both work and how you would respond clearly. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"どちらでも問題ない2つの予定と、分かりやすい返答について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about two plans that would both work and how you would respond clearly. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"どちらでも問題ない2つの予定と、分かりやすい返答について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Either one works for me.","Both options are fine.","I’m available on …"],"vocabulary":["either","both","option","available"]},{"key":"strong-preference","title_en":"What you would rather do","title_ja":"どちらかを選ぶなら","description_en":"A choice where you would clearly rather do one thing than the other.","description_ja":"2つの選択肢のうち、はっきり一方を選びたい場面","speaking_prompt_en":"Speak for 60–90 seconds about a choice where you would clearly rather do one thing than the other. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"2つの選択肢のうち、はっきり一方を選びたい場面について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a choice where you would clearly rather do one thing than the other. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"2つの選択肢のうち、はっきり一方を選びたい場面について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I would rather …","I’d prefer to …","The reason is …"],"vocabulary":["rather","preference","convenient","priority"]},{"key":"neither-option","title_en":"When neither works","title_ja":"どちらも合わないとき","description_en":"How to respond politely when neither of two suggestions works for you.","description_ja":"2つの提案がどちらも合わないときの、丁寧な返し方","speaking_prompt_en":"Speak for 60–90 seconds about how to respond politely when neither of two suggestions works for you. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"2つの提案がどちらも合わないときの、丁寧な返し方について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how to respond politely when neither of two suggestions works for you. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"2つの提案がどちらも合わないときの、丁寧な返し方について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Neither option works for me.","Could we consider …?","Would another day be possible?"],"vocabulary":["neither","alternative","conflict","suggestion"]}]'::jsonb),
    ('july-22', '[{"key":"meeting-time","title_en":"Finding a meeting time","title_ja":"会う時間を決める","description_en":"How you would arrange a meeting time that works for everyone.","description_ja":"全員に都合のよい会議時間を決める方法","speaking_prompt_en":"Speak for 60–90 seconds about how you would arrange a meeting time that works for everyone. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"全員に都合のよい会議時間を決める方法について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how you would arrange a meeting time that works for everyone. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"全員に都合のよい会議時間を決める方法について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Would you be available …?","That time works for me.","Could we move it to …?"],"vocabulary":["availability","appointment","schedule","reschedule"]},{"key":"clear-answer","title_en":"A clear yes or no","title_ja":"分かりやすいYes・No","description_en":"Why clear answers matter when someone asks a negative question.","description_ja":"否定疑問文を聞かれたとき、明確に答えることが大切な理由","speaking_prompt_en":"Speak for 60–90 seconds about why clear answers matter when someone asks a negative question. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"否定疑問文を聞かれたとき、明確に答えることが大切な理由について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about why clear answers matter when someone asks a negative question. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"否定疑問文を聞かれたとき、明確に答えることが大切な理由について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["Yes, I am.","No, I’m not.","To be clear, …"],"vocabulary":["negative question","confirm","confusion","direct"]},{"key":"flexible-choice","title_en":"Being flexible","title_ja":"柔軟に選ぶ","description_en":"A situation where either of two choices is genuinely fine for you.","description_ja":"2つの選択肢のどちらでも本当に問題ない場面","speaking_prompt_en":"Speak for 60–90 seconds about a situation where either of two choices is genuinely fine for you. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"2つの選択肢のどちらでも本当に問題ない場面について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a situation where either of two choices is genuinely fine for you. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"2つの選択肢のどちらでも本当に問題ない場面について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Either is fine.","I don’t mind which one.","Whatever works best for you."],"vocabulary":["flexible","preference","arrangement","convenient"]}]'::jsonb),
    ('july-23', '[{"key":"under-weather","title_en":"Feeling under the weather","title_ja":"少し体調が悪いとき","description_en":"How you change your plans when you feel slightly unwell.","description_ja":"少し体調が悪いときに、予定をどう変更するか","speaking_prompt_en":"Speak for 60–90 seconds about how you change your plans when you feel slightly unwell. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"少し体調が悪いときに、予定をどう変更するかについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how you change your plans when you feel slightly unwell. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"少し体調が悪いときに、予定をどう変更するかについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I’m feeling under the weather.","I might need to rest.","Can we do it another day?"],"vocabulary":["symptom","rest","recover","postpone"]},{"key":"future-invention","title_en":"A useful future invention","title_ja":"未来の便利な発明","description_en":"A Doraemon-style gadget that would solve a real everyday problem.","description_ja":"日常の困りごとを解決する、ドラえもんの道具のような発明","speaking_prompt_en":"Speak for 60–90 seconds about a Doraemon-style gadget that would solve a real everyday problem. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"日常の困りごとを解決する、ドラえもんの道具のような発明について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a Doraemon-style gadget that would solve a real everyday problem. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"日常の困りごとを解決する、ドラえもんの道具のような発明について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["It would allow people to …","I haven’t thought of a name yet.","It could be useful when …"],"vocabulary":["gadget","invention","convenient","imagine"]},{"key":"movement-habit","title_en":"An everyday movement habit","title_ja":"日常の動作習慣","description_en":"A healthy movement or exercise habit you have started or want to start.","description_ja":"始めた、または始めたい健康的な運動習慣","speaking_prompt_en":"Speak for 60–90 seconds about a healthy movement or exercise habit you have started or want to start. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"始めた、または始めたい健康的な運動習慣について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a healthy movement or exercise habit you have started or want to start. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"始めた、または始めたい健康的な運動習慣について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I’ve started …","I haven’t done it regularly yet.","It helps me …"],"vocabulary":["routine","stretch","movement","regularly"]}]'::jsonb),
    ('july-25', '[{"key":"changing-feeling","title_en":"A feeling that changed","title_ja":"変化した気持ち","description_en":"How your feeling gradually changed during an event or experience.","description_ja":"出来事や経験の中で、気持ちが少しずつ変わったこと","speaking_prompt_en":"Speak for 60–90 seconds about how your feeling gradually changed during an event or experience. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"出来事や経験の中で、気持ちが少しずつ変わったことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how your feeling gradually changed during an event or experience. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"出来事や経験の中で、気持ちが少しずつ変わったことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I was getting …","At first, I felt …","By the end, …"],"vocabulary":["gradually","emotion","nervous","relieved"]},{"key":"gut-decision","title_en":"Following your intuition","title_ja":"直感を信じた判断","description_en":"A decision where you trusted, or chose not to trust, a gut feeling.","description_ja":"直感を信じた、または信じなかった判断","speaking_prompt_en":"Speak for 60–90 seconds about a decision where you trusted, or chose not to trust, a gut feeling. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"直感を信じた、または信じなかった判断について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a decision where you trusted, or chose not to trust, a gut feeling. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"直感を信じた、または信じなかった判断について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I had a gut feeling that …","Something didn’t feel right.","I decided to trust …"],"vocabulary":["intuition","instinct","risk","decision"]},{"key":"body-signal","title_en":"Listening to body signals","title_ja":"体のサインに気づく","description_en":"How signals such as hunger or tiredness affect your choices.","description_ja":"空腹や疲れなどの体のサインが、選択にどう影響するか","speaking_prompt_en":"Speak for 60–90 seconds about how signals such as hunger or tiredness affect your choices. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"空腹や疲れなどの体のサインが、選択にどう影響するかについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about how signals such as hunger or tiredness affect your choices. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"空腹や疲れなどの体のサインが、選択にどう影響するかについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I’m getting hungry.","I’m starting to feel tired.","I should probably …"],"vocabulary":["appetite","energy","signal","well-being"]}]'::jsonb),
    ('july-26', '[{"key":"realistic-hope","title_en":"A realistic hope","title_ja":"実現できそうな希望","description_en":"Something you hope will happen and the action you can take toward it.","description_ja":"実現してほしいことと、そのために自分ができる行動","speaking_prompt_en":"Speak for 60–90 seconds about something you hope will happen and the action you can take toward it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"実現してほしいことと、そのために自分ができる行動について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about something you hope will happen and the action you can take toward it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"実現してほしいことと、そのために自分ができる行動について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I hope I can …","I’m working toward …","There’s a good chance …"],"vocabulary":["hope","opportunity","effort","realistic"]},{"key":"present-wish","title_en":"A wish about now","title_ja":"今についての願い","description_en":"Something you wish were different in your present situation.","description_ja":"今の状況で、違っていたらよいと思うこと","speaking_prompt_en":"Speak for 60–90 seconds about something you wish were different in your present situation. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"今の状況で、違っていたらよいと思うことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about something you wish were different in your present situation. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"今の状況で、違っていたらよいと思うことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I wish I were …","If only I had …","Right now, …"],"vocabulary":["wish","situation","impossible","change"]},{"key":"past-regret","title_en":"Learning from a regret","title_ja":"過去の後悔から学ぶ","description_en":"A past choice you wish you had handled differently and what you learned.","description_ja":"違う対応をすればよかったと思う過去の選択と、そこから学んだこと","speaking_prompt_en":"Speak for 60–90 seconds about a past choice you wish you had handled differently and what you learned. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"違う対応をすればよかったと思う過去の選択と、そこから学んだことについて60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a past choice you wish you had handled differently and what you learned. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"違う対応をすればよかったと思う過去の選択と、そこから学んだことについて100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["I wish I had …","I should have …","Since then, I’ve …"],"vocabulary":["regret","consequence","lesson","reflect"]}]'::jsonb),
    ('july-27', '[{"key":"small-accident","title_en":"A small accident","title_ja":"小さなアクシデント","description_en":"A small spill, splash or mistake and how you dealt with it.","description_ja":"こぼす・水がかかるなどの小さな失敗と、その後の対応","speaking_prompt_en":"Speak for 60–90 seconds about a small spill, splash or mistake and how you dealt with it. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"こぼす・水がかかるなどの小さな失敗と、その後の対応について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a small spill, splash or mistake and how you dealt with it. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"こぼす・水がかかるなどの小さな失敗と、その後の対応について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["I accidentally spilled …","It splashed onto …","I cleaned it up by …"],"vocabulary":["spill","pour","splash","accidentally"]},{"key":"acquired-taste","title_en":"An acquired taste","title_ja":"だんだん好きになったもの","description_en":"A food, drink or activity you learned to enjoy gradually.","description_ja":"少しずつ好きになった食べ物・飲み物・活動","speaking_prompt_en":"Speak for 60–90 seconds about a food, drink or activity you learned to enjoy gradually. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"少しずつ好きになった食べ物・飲み物・活動について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a food, drink or activity you learned to enjoy gradually. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"少しずつ好きになった食べ物・飲み物・活動について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Core","phrases":["It is an acquired taste.","I didn’t like it at first.","Now I appreciate …"],"vocabulary":["flavour","bitter","gradually","appreciate"]},{"key":"tense-story","title_en":"Telling the full story","title_ja":"時制を使い分ける物語","description_en":"A short story that clearly connects what happened before, during and afterward.","description_ja":"出来事の前・最中・その後を、時制を分けて伝える短い話","speaking_prompt_en":"Speak for 60–90 seconds about a short story that clearly connects what happened before, during and afterward. Give one concrete example and explain why it matters to you.","speaking_prompt_ja":"出来事の前・最中・その後を、時制を分けて伝える短い話について60〜90秒で話してください。具体例を1つ挙げ、自分にとってなぜ大切かも説明しましょう。","essay_prompt_en":"Write 100–180 words about a short story that clearly connects what happened before, during and afterward. Give a clear reason, one supporting example and a final takeaway.","essay_prompt_ja":"出来事の前・最中・その後を、時制を分けて伝える短い話について100〜180語で書いてください。理由・具体例・最後のまとめを入れましょう。","challenge":"Stretch","phrases":["Before that, I had …","While I was …","Since then, I have …"],"vocabulary":["sequence","background","result","timeline"]}]'::jsonb)
  )
  update public.review_premium_tasks t
  set topics = source.topics,
      updated_at = now()
  from public.review_lessons l, source
  where t.lesson_id = l.id
    and l.slug = source.slug
    and t.stable_key in (
      l.slug || '-premium-speaking-v1',
      l.slug || '-premium-essay-v1'
    );
  get diagnostics updated_count = row_count;
  if updated_count <> 34 then
    raise exception 'Premium topic update incomplete: expected 34 tasks, updated %.', updated_count;
  end if;
end;
$topics$;

create or replace function public.review_validate_submission_topic()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  task_topics jsonb;
begin
  select t.topics into task_topics
  from public.review_premium_tasks t
  where t.id = new.task_id;

  task_topics := coalesce(task_topics, '[]'::jsonb);
  if new.selected_topic_key is not null and not exists (
    select 1
    from jsonb_array_elements(task_topics) item
    where item ->> 'key' = btrim(new.selected_topic_key)
  ) then
    raise exception 'Choose a topic offered for this Premium task.';
  end if;

  if new.status = 'submitted'
     and jsonb_array_length(task_topics) > 0
     and nullif(btrim(coalesce(new.selected_topic_key, '')), '') is null then
    raise exception 'Choose a topic before submitting this Premium task.';
  end if;

  if tg_op = 'UPDATE'
     and old.status not in ('draft', 'returned')
     and new.selected_topic_key is distinct from old.selected_topic_key then
    raise exception 'The selected topic is locked while the teacher reviews this submission.';
  end if;
  return new;
end;
$function$;

revoke all on function public.review_validate_submission_topic() from public;

drop trigger if exists review_task_submissions_topic_validate
  on public.review_task_submissions;
create trigger review_task_submissions_topic_validate
before insert or update on public.review_task_submissions
for each row execute function public.review_validate_submission_topic();

do $verify$
declare
  covered_tasks integer;
  invalid_topics integer;
  invalid_topic_sets integer;
begin
  select count(*) into covered_tasks
  from public.review_premium_tasks t
  join public.review_lessons l on l.id = t.lesson_id
  where t.active
    and t.stable_key in (
      l.slug || '-premium-speaking-v1',
      l.slug || '-premium-essay-v1'
    )
    and jsonb_array_length(t.topics) = 3;

  select count(*) into invalid_topics
  from public.review_premium_tasks t
  join public.review_lessons l on l.id = t.lesson_id
  cross join lateral jsonb_array_elements(t.topics) item
  where t.active
    and t.stable_key in (
      l.slug || '-premium-speaking-v1',
      l.slug || '-premium-essay-v1'
    )
    and (
      jsonb_typeof(item) <> 'object'
      or nullif(btrim(item ->> 'key'), '') is null
      or nullif(btrim(item ->> 'title_en'), '') is null
      or nullif(btrim(item ->> 'title_ja'), '') is null
      or nullif(btrim(item ->> 'description_en'), '') is null
      or nullif(btrim(item ->> 'description_ja'), '') is null
      or nullif(btrim(item ->> 'speaking_prompt_en'), '') is null
      or nullif(btrim(item ->> 'speaking_prompt_ja'), '') is null
      or nullif(btrim(item ->> 'essay_prompt_en'), '') is null
      or nullif(btrim(item ->> 'essay_prompt_ja'), '') is null
      or jsonb_typeof(item -> 'phrases') <> 'array'
      or jsonb_array_length(item -> 'phrases') not between 3 and 6
      or jsonb_typeof(item -> 'vocabulary') <> 'array'
      or jsonb_array_length(item -> 'vocabulary') not between 3 and 8
    );

  select count(*) into invalid_topic_sets
  from public.review_premium_tasks t
  join public.review_lessons l on l.id = t.lesson_id
  where t.active
    and t.stable_key in (
      l.slug || '-premium-speaking-v1',
      l.slug || '-premium-essay-v1'
    )
    and (
      jsonb_array_length(t.topics) <> 3
      or (select count(distinct item ->> 'key') from jsonb_array_elements(t.topics) item) <> 3
    );

  if covered_tasks <> 34 or invalid_topics <> 0 or invalid_topic_sets <> 0 then
    raise exception 'Premium topic verification failed: covered %, invalid topics %, invalid sets %.',
      covered_tasks, invalid_topics, invalid_topic_sets;
  end if;
end;
$verify$;

comment on column public.review_premium_tasks.topics is
  'Learner-safe bilingual topic choices with topic-specific prompts, phrases and vocabulary.';
comment on column public.review_task_submissions.selected_topic_key is
  'The stable topic chosen by the learner for this attempt.';
